var data = {
    categories: ['Rap', 'Trap', 'Cloud Rap'],
    max_rating: 5,
    songs: [{
        src: 'mp3/desaccorde.mp3',
        title: 'Désaccordé',
        duration: '3:31',
        author: 'Vald',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 5,
        category: 'Rap',
        img: 'N/A',
        id: 'songOne',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/arbredevie.mp3',
        title: 'Arbre de vie',
        duration: '4:13',
        author: 'Sopico',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songTwo',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/113.mp3',
        title: '113',
        duration: '2:32',
        author: 'Booba',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songThree',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/ecailles.mp3',
        title: 'Ecailles',
        duration: '3:00',
        author: 'Vald',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songFour',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/chaos.mp3',
        title: 'Chaos',
        duration: '2:25',
        author: 'Django',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songFive',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/jfumetrop.mp3',
        title: "J'fume trop",
        duration: '2:58',
        author: 'DIL ft. 2Cheese',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songSix',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/longuevie.mp3',
        title: 'Longue vie',
        duration: '3:29',
        author: 'Sofiane',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songSeven',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/gizeh.mp3',
        title: 'Gizeh',
        duration: '3:19',
        author: 'Vald',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songEight',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/imback.mp3',
        title: "I'm back",
        duration: '3:26',
        author: 'Dr. Dre',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'EN',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songNine',
        playlist: ['rapstr', 'top50str'],
      },
      {
        src: 'mp3/plushaut.mp3',
        title: "Plus haut",
        duration: '6:27',
        author: 'Alkpote ft. Vald',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songTen',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/jelevelamoto.mp3',
        title: "Je lève la moto",
        duration: '4:48',
        author: 'Jul',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songEleven',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/sombresoiree.mp3',
        title: "Sombre soirée",
        duration: '3:43',
        author: 'Vald',
        author_url: '',
        description: ' “',
        year: 2018,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songTwelve',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/martineden.mp3',
        title: "Martin Eden",
        duration: '4:52',
        author: 'Nekfeu',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songThirteen',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/kingsdead.mp3',
        title: "King's dead",
        duration: '3:50',
        author: 'Jay Rock ft. Kendrick Lamar',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'EN',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songFourteen',
        playlist: ['rapstr', 'top50str'],
      },
      {
        src: 'mp3/pentacleetbougie.mp3',
        title: "Pentacle et bougie",
        duration: '3:29',
        author: 'Vald',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songFifteen',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/mosaiquesolitaire.mp3',
        title: "Mosaïque solitaire",
        duration: '5:05',
        author: 'Damso',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songSixteen',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/fichu.mp3',
        title: "Fichu",
        duration: '2:33',
        author: 'Django',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songSeventeen',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/evitela.mp3',
        title: "Evite la",
        duration: '3:34',
        author: 'Sneazzy ft. S.Pri Noir',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songEightteen',
        playlist: ['rapfr', 'top50fr'],
      },
      {
        src: 'mp3/babysquirt.mp3',
        title: "Baby squirt",
        duration: '3:37',
        author: 'Vald',
        author_url: '',
        description: ' “',
        year: 2017,
        audio_language: 'FR',
        rating: 4,
        category: 'Rap',
        img: 'N/A',
        id: 'songNineteen',
        playlist: ['rapfr', 'top50fr'],
      },
    ]
  };
